[gcp_service_account]
type = "service_account"
project_id = "un-policy-architect"
private_key_id = "8766944085b27414ba0b8914e81997303e46a69f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCQ0+G9HK37+XZw
XXHFN9otuGL7iFgwYvdfqOHP3gXcOmI/Br2fCapp0ibv+qX80+mMwihQgIdEI+Ym
4lMMGyK1vZc/lPTC4SHpuXO3DXGK6tsK9xNlI06ewop6OWHe9cWO8ukK5Vyvowrc
+ORTs7vcVi3CFPdZ0OEdOjbIZT6/ENFnn+gRsoS+9i/m83L59dzlo75L057Tufio
o7Zv/dgyPKDa9jCv2toS7tlyfWUmqV8UcGdGz5Xym6BDlgQ2A9Gdw63wdw9Cs0+G
TN+TKPt709yzchs9wtXaFVKdwtisVuF79gS773H/7tsKejg30imQCG9PNoacqw3k
BkFXWEt3AgMBAAECggEACLc3lpHrRoa0wf5domjCEI5QJqMF66OJD5CyRjguUhqR
Xwmgz7ldMBEdlsOWyahXHclxc6bIfSlL6HsmVEwtwpIuT/0+3Zt+1vn6JMICW0HW
/MnxuNxvFs7OVpytbyWLRhcIP0eeVFOTi8jOtNrUK2ZkSpHIcPdJFOEz+stdA1KA
j3rL/eKHnYFU3CrW6U73Ao56/688vuX5KMUfsMyllkkyU/F2QNdVZftZz0eaqKCL
cgPOvvQOH5dp4Nj6cUTAp/j/fglVUpleuAmUnVJC6Hq2JjbkrbuQKeGtalhXg+fL
wPpByOKi90d4muPcoYmGDeF7oXpuXX1lkUiLwCEqAQKBgQDMvfY50JNyfRVmuuhW
k+JWw5ncicz/hQqxq33zssmYY6mtQb8OJJHhBZFyiAG5Q6SDpPq8o5lkOHHc3svo
Zv6iisAI6NNgofungKUDYD0rHkOADui2YGM/3gcSxMrg9xQQt/eAlAzGoOWpPRcJ
Nr4ZtZG/rWraLHcJq/xEzmwDYQKBgQC1FfjnVG4pn0kBamASQ2xMZS/yfmArHKiF
5u4rP0Jfz7EHhDLWlMndtIVmOdbv5WhK6YlZc8a9sX7T/k7UAOwiThqG+ZDFOG3V
oGDwAJ/8U1VBD7K/b8qxJwkaMvKndv5LQ1grrQz/40qhSsLCpUmSv33bk+avjx19
S1/bxuqV1wKBgQCXIHT6kfn0XV4JuVc8aOZ+Mt2Ei3b0+Ug+gx5yXvstcAtT5x7W
mqnPVmPZDYlwLfzma0XlLkFQV9W8Ofx7bGLyqcY8DVfRkV+HcY7cIhKknC8o/FhM
HnPENeg0s2wpiFeYS6L2ltGjYCqFtKEnXPAPXBXcTW584qtvSTLpuxDBoQKBgE4w
C4WOjfZIwVPsI0kfdX5S3m38pPdYa2dNe56OtND7sztEmFLQcYzZqhOme6ifS/W0
ekp2U+SJ4/ISxuSA9XQmdwu6bAjLwZjQo6pdCrb/IDt0VMCVu1XcPfDi+KTYGxpS
HJrXIFrIP+v+hLNYfLjxF52ccalxyNDVn7EcZSOHAoGBALoE8G41nB+fAN72PsU3
idDZn2XIzQsZjkik/KON1k7MKCMRceeq0XSqkW3BDwsXPRkXiU+JlYuUws/mojds
JLoyloRSouoP+X82yqurovHF1275npvg+PJ4plpTm3yo60cg72p9fx7n6WwqX0s6
RtXu5QrOm9VvLXgB3yGHxm6V
-----END PRIVATE KEY-----"""
client_email = "un-policy-bot@un-policy-architect.iam.gserviceaccount.com"
client_id = "101081456467645154473"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/un-policy-bot%40un-policy-architect.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
